# Generated by Django 4.0.6 on 2022-09-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.CharField(choices=[('Y', '是'), ('N', '否')], default='Y', max_length=3),
        ),
    ]
