# Generated by Django 4.0.6 on 2022-09-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_member_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subject',
            field=models.CharField(blank=True, choices=[('biology', 'DSE-生物'), ('chinese', 'DSE-中文'), ('english', 'DSE-英文'), ('c-hist', 'DSE-中史'), ('hist', 'DSE-世史'), ('ielts', 'IELTS'), ('math', 'DSE-數學'), ('chem', 'DSE-化學'), ('it', 'DSE-資訊科技'), ('ls', 'DSE-通識'), ('sat', 'SAT'), ('a-level', 'A-Level'), ('uni', '大專補習')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('F', '女'), ('M', '男')], default='NONE', max_length=7),
        ),
    ]
