# Generated by Django 4.0.6 on 2022-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_member_price_alter_member_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(default='', max_length=56),
        ),
        migrations.AddField(
            model_name='member',
            name='mode',
            field=models.CharField(choices=[('FTF', '面授 (不上門)'), ('FEFH', '面授 (上門）'), ('Online', '線上上課')], default='FTF', max_length=6),
        ),
        migrations.AddField(
            model_name='member',
            name='referral',
            field=models.CharField(choices=[('Y', '是'), ('N', '否')], default='Y', max_length=3),
        ),
        migrations.AddField(
            model_name='member',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
