# Generated by Django 4.0.6 on 2022-09-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_member_location_member_mode_member_referral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mode',
            field=models.CharField(choices=[('FTF', '面授 (不上門)'), ('FEFH', '面授 (上門)'), ('Online', '線上上課')], default='FTF', max_length=6),
        ),
        migrations.AlterField(
            model_name='member',
            name='referral',
            field=models.CharField(choices=[('A', '是'), ('D', '否')], default='A', max_length=3),
        ),
    ]
