# Generated by Django 4.0.6 on 2022-09-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_member_referral_alter_member_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='consent',
            field=models.CharField(choices=[('ACEEPT', '同意'), ('DECLINE', '拒絕')], default='ACEEPT', max_length=8),
        ),
    ]
