# Generated by Django 4.0.6 on 2022-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_member_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_num',
            field=models.CharField(default='', max_length=8),
        ),
    ]
