# Generated by Django 4.0.6 on 2022-10-02 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
