# Generated by Django 4.0.6 on 2022-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='links',
            field=models.JSONField(blank=True, default=None),
        ),
    ]
