# Generated by Django 4.0.6 on 2022-08-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_sitecontent_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecontent',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='links',
        ),
    ]
